language: python
python:
    - "3.5"
    - "3.7"
    - "3.8"
    - "3.9"
services:
    - docker
install:
    - pip install -r master/python/requirements.txt
    - pip install -r agent/python/requirements.txt
    - pip install -e .
script:
    - cd test
    - pytest
