/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _WrapperMessage_Type {
    WrapperMessage_Type_PING = 0,
    WrapperMessage_Type_PONG = 1,
    WrapperMessage_Type_RUN_TASK = 2,
    WrapperMessage_Type_KILL_TASK = 3,
    WrapperMessage_Type_RESOURCE_OFFER = 4,
    WrapperMessage_Type_RESOURCE_REQUEST = 5
} WrapperMessage_Type;

typedef enum _Value_Type {
    Value_Type_SCALAR = 0,
    Value_Type_RANGES = 1,
    Value_Type_SET = 2,
    Value_Type_TEXT = 3,
    Value_Type_DEVICE = 4
} Value_Type;

typedef enum _ContainerInfo_Type {
    ContainerInfo_Type_DOCKER = 1,
    ContainerInfo_Type_WASM = 2
} ContainerInfo_Type;

typedef enum _ContainerInfo_DockerInfo_Network {
    ContainerInfo_DockerInfo_Network_HOST = 1,
    ContainerInfo_DockerInfo_Network_BRIDGE = 2,
    ContainerInfo_DockerInfo_Network_NONE = 3,
    ContainerInfo_DockerInfo_Network_USER = 4
} ContainerInfo_DockerInfo_Network;

typedef enum _TaskInfo_TaskState {
    TaskInfo_TaskState_COMPLETED = 0,
    TaskInfo_TaskState_ERRORED = 1,
    TaskInfo_TaskState_RUNNING = 2,
    TaskInfo_TaskState_ISSUED = 3,
    TaskInfo_TaskState_UNISSUED = 4,
    TaskInfo_TaskState_STARTING = 5,
    TaskInfo_TaskState_KILLED = 6
} TaskInfo_TaskState;

/* Struct definitions */
typedef struct _ContainerInfo_WASMInfo {
    pb_callback_t wasm_binary;
    pb_callback_t environment;
} ContainerInfo_WASMInfo;

typedef struct _FrameworkInfo {
    pb_callback_t name;
    pb_callback_t framework_id;
} FrameworkInfo;

typedef struct _Offer {
    pb_callback_t id;
    pb_callback_t framework_id;
    pb_callback_t agent_id;
    pb_callback_t resources;
    pb_callback_t attributes;
} Offer;

typedef struct _OfferID {
    pb_callback_t value;
} OfferID;

typedef struct _ResourceOfferMessage {
    pb_callback_t framework_id;
    pb_callback_t offers;
} ResourceOfferMessage;

typedef struct _ResourceRequestMessage {
    pb_callback_t framework_id;
} ResourceRequestMessage;

typedef struct _Value_Device {
    pb_callback_t device;
} Value_Device;

typedef struct _Value_Ranges {
    pb_callback_t range;
} Value_Ranges;

typedef struct _Value_Set {
    pb_callback_t item;
} Value_Set;

typedef struct _Value_Text {
    pb_callback_t value;
} Value_Text;

typedef struct _AgentInfo {
    pb_callback_t resources;
    pb_callback_t attributes;
    pb_callback_t id;
    pb_callback_t name;
    bool has_ping_rate;
    int32_t ping_rate;
} AgentInfo;

typedef struct _ContainerInfo_DockerInfo {
    pb_callback_t image;
    bool has_network;
    ContainerInfo_DockerInfo_Network network;
    pb_callback_t port_mappings;
    bool has_force_pull_image;
    bool force_pull_image;
    pb_callback_t environment_variables;
} ContainerInfo_DockerInfo;

typedef struct _ContainerInfo_DockerInfo_PortMapping {
    uint32_t host_port;
    uint32_t container_port;
    pb_callback_t protocol;
} ContainerInfo_DockerInfo_PortMapping;

typedef struct _ContainerInfo_WASMInfo_EnvironmentVariable {
    pb_callback_t key;
    bool has_value;
    int32_t value;
    pb_callback_t str_value;
} ContainerInfo_WASMInfo_EnvironmentVariable;

typedef struct _KillTaskMessage {
    pb_callback_t name;
    pb_callback_t task_id;
    pb_callback_t agent_id;
    FrameworkInfo framework;
} KillTaskMessage;

typedef struct _Value_Range {
    uint64_t begin;
    uint64_t end;
} Value_Range;

typedef struct _Value_Scalar {
    double value;
} Value_Scalar;

typedef struct _Attribute {
    pb_callback_t name;
    Value_Type type;
    bool has_scalar;
    Value_Scalar scalar;
    bool has_ranges;
    Value_Ranges ranges;
    bool has_text;
    Value_Text text;
    bool has_set;
    Value_Set set;
} Attribute;

typedef struct _ContainerInfo {
    ContainerInfo_Type type;
    bool has_docker;
    ContainerInfo_DockerInfo docker;
    bool has_wasm;
    ContainerInfo_WASMInfo wasm;
} ContainerInfo;

typedef struct _PingAgentMessage {
    AgentInfo agent;
    pb_callback_t tasks;
} PingAgentMessage;

typedef struct _Resource {
    pb_callback_t name;
    Value_Type type;
    bool has_scalar;
    Value_Scalar scalar;
    bool has_ranges;
    Value_Ranges ranges;
    bool has_set;
    Value_Set set;
    bool has_shared;
    bool shared;
    bool has_text;
    Value_Text text;
    bool has_device;
    Value_Device device;
} Resource;

typedef struct _Value {
    Value_Type type;
    bool has_scalar;
    Value_Scalar scalar;
    bool has_ranges;
    Value_Ranges ranges;
    bool has_set;
    Value_Set set;
    bool has_text;
    Value_Text text;
    bool has_device;
    Value_Device device;
} Value;

typedef struct _TaskInfo {
    pb_callback_t name;
    pb_callback_t task_id;
    pb_callback_t agent_id;
    pb_callback_t resources;
    FrameworkInfo framework;
    bool has_state;
    TaskInfo_TaskState state;
    pb_callback_t error_message;
    ContainerInfo container;
} TaskInfo;

typedef struct _RunTaskMessage {
    TaskInfo task;
} RunTaskMessage;

typedef struct _PongAgentMessage {
    pb_callback_t agent_id;
    bool has_run_task;
    RunTaskMessage run_task;
    bool has_kill_task;
    KillTaskMessage kill_task;
} PongAgentMessage;

typedef struct _WrapperMessage {
    WrapperMessage_Type type;
    bool has_ping;
    PingAgentMessage ping;
    bool has_pong;
    PongAgentMessage pong;
    bool has_run_task;
    RunTaskMessage run_task;
    bool has_kill_task;
    KillTaskMessage kill_task;
    bool has_offermsg;
    ResourceOfferMessage offermsg;
    bool has_request;
    ResourceRequestMessage request;
} WrapperMessage;


/* Helper constants for enums */
#define _WrapperMessage_Type_MIN WrapperMessage_Type_PING
#define _WrapperMessage_Type_MAX WrapperMessage_Type_RESOURCE_REQUEST
#define _WrapperMessage_Type_ARRAYSIZE ((WrapperMessage_Type)(WrapperMessage_Type_RESOURCE_REQUEST+1))

#define _Value_Type_MIN Value_Type_SCALAR
#define _Value_Type_MAX Value_Type_DEVICE
#define _Value_Type_ARRAYSIZE ((Value_Type)(Value_Type_DEVICE+1))

#define _ContainerInfo_Type_MIN ContainerInfo_Type_DOCKER
#define _ContainerInfo_Type_MAX ContainerInfo_Type_WASM
#define _ContainerInfo_Type_ARRAYSIZE ((ContainerInfo_Type)(ContainerInfo_Type_WASM+1))

#define _ContainerInfo_DockerInfo_Network_MIN ContainerInfo_DockerInfo_Network_HOST
#define _ContainerInfo_DockerInfo_Network_MAX ContainerInfo_DockerInfo_Network_USER
#define _ContainerInfo_DockerInfo_Network_ARRAYSIZE ((ContainerInfo_DockerInfo_Network)(ContainerInfo_DockerInfo_Network_USER+1))

#define _TaskInfo_TaskState_MIN TaskInfo_TaskState_COMPLETED
#define _TaskInfo_TaskState_MAX TaskInfo_TaskState_KILLED
#define _TaskInfo_TaskState_ARRAYSIZE ((TaskInfo_TaskState)(TaskInfo_TaskState_KILLED+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define WrapperMessage_init_default              {_WrapperMessage_Type_MIN, false, PingAgentMessage_init_default, false, PongAgentMessage_init_default, false, RunTaskMessage_init_default, false, KillTaskMessage_init_default, false, ResourceOfferMessage_init_default, false, ResourceRequestMessage_init_default}
#define PingAgentMessage_init_default            {AgentInfo_init_default, {{NULL}, NULL}}
#define PongAgentMessage_init_default            {{{NULL}, NULL}, false, RunTaskMessage_init_default, false, KillTaskMessage_init_default}
#define AgentInfo_init_default                   {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define Resource_init_default                    {{{NULL}, NULL}, _Value_Type_MIN, false, Value_Scalar_init_default, false, Value_Ranges_init_default, false, Value_Set_init_default, false, 0, false, Value_Text_init_default, false, Value_Device_init_default}
#define Attribute_init_default                   {{{NULL}, NULL}, _Value_Type_MIN, false, Value_Scalar_init_default, false, Value_Ranges_init_default, false, Value_Text_init_default, false, Value_Set_init_default}
#define Value_init_default                       {_Value_Type_MIN, false, Value_Scalar_init_default, false, Value_Ranges_init_default, false, Value_Set_init_default, false, Value_Text_init_default, false, Value_Device_init_default}
#define Value_Scalar_init_default                {0}
#define Value_Range_init_default                 {0, 0}
#define Value_Ranges_init_default                {{{NULL}, NULL}}
#define Value_Set_init_default                   {{{NULL}, NULL}}
#define Value_Text_init_default                  {{{NULL}, NULL}}
#define Value_Device_init_default                {{{NULL}, NULL}}
#define ContainerInfo_init_default               {_ContainerInfo_Type_MIN, false, ContainerInfo_DockerInfo_init_default, false, ContainerInfo_WASMInfo_init_default}
#define ContainerInfo_DockerInfo_init_default    {{{NULL}, NULL}, false, ContainerInfo_DockerInfo_Network_HOST, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define ContainerInfo_DockerInfo_PortMapping_init_default {0, 0, {{NULL}, NULL}}
#define ContainerInfo_WASMInfo_init_default      {{{NULL}, NULL}, {{NULL}, NULL}}
#define ContainerInfo_WASMInfo_EnvironmentVariable_init_default {{{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define FrameworkInfo_init_default               {{{NULL}, NULL}, {{NULL}, NULL}}
#define TaskInfo_init_default                    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, FrameworkInfo_init_default, false, _TaskInfo_TaskState_MIN, {{NULL}, NULL}, ContainerInfo_init_default}
#define RunTaskMessage_init_default              {TaskInfo_init_default}
#define KillTaskMessage_init_default             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, FrameworkInfo_init_default}
#define ResourceRequestMessage_init_default      {{{NULL}, NULL}}
#define ResourceOfferMessage_init_default        {{{NULL}, NULL}, {{NULL}, NULL}}
#define Offer_init_default                       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define OfferID_init_default                     {{{NULL}, NULL}}
#define WrapperMessage_init_zero                 {_WrapperMessage_Type_MIN, false, PingAgentMessage_init_zero, false, PongAgentMessage_init_zero, false, RunTaskMessage_init_zero, false, KillTaskMessage_init_zero, false, ResourceOfferMessage_init_zero, false, ResourceRequestMessage_init_zero}
#define PingAgentMessage_init_zero               {AgentInfo_init_zero, {{NULL}, NULL}}
#define PongAgentMessage_init_zero               {{{NULL}, NULL}, false, RunTaskMessage_init_zero, false, KillTaskMessage_init_zero}
#define AgentInfo_init_zero                      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define Resource_init_zero                       {{{NULL}, NULL}, _Value_Type_MIN, false, Value_Scalar_init_zero, false, Value_Ranges_init_zero, false, Value_Set_init_zero, false, 0, false, Value_Text_init_zero, false, Value_Device_init_zero}
#define Attribute_init_zero                      {{{NULL}, NULL}, _Value_Type_MIN, false, Value_Scalar_init_zero, false, Value_Ranges_init_zero, false, Value_Text_init_zero, false, Value_Set_init_zero}
#define Value_init_zero                          {_Value_Type_MIN, false, Value_Scalar_init_zero, false, Value_Ranges_init_zero, false, Value_Set_init_zero, false, Value_Text_init_zero, false, Value_Device_init_zero}
#define Value_Scalar_init_zero                   {0}
#define Value_Range_init_zero                    {0, 0}
#define Value_Ranges_init_zero                   {{{NULL}, NULL}}
#define Value_Set_init_zero                      {{{NULL}, NULL}}
#define Value_Text_init_zero                     {{{NULL}, NULL}}
#define Value_Device_init_zero                   {{{NULL}, NULL}}
#define ContainerInfo_init_zero                  {_ContainerInfo_Type_MIN, false, ContainerInfo_DockerInfo_init_zero, false, ContainerInfo_WASMInfo_init_zero}
#define ContainerInfo_DockerInfo_init_zero       {{{NULL}, NULL}, false, _ContainerInfo_DockerInfo_Network_MIN, {{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define ContainerInfo_DockerInfo_PortMapping_init_zero {0, 0, {{NULL}, NULL}}
#define ContainerInfo_WASMInfo_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}}
#define ContainerInfo_WASMInfo_EnvironmentVariable_init_zero {{{NULL}, NULL}, false, 0, {{NULL}, NULL}}
#define FrameworkInfo_init_zero                  {{{NULL}, NULL}, {{NULL}, NULL}}
#define TaskInfo_init_zero                       {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, FrameworkInfo_init_zero, false, _TaskInfo_TaskState_MIN, {{NULL}, NULL}, ContainerInfo_init_zero}
#define RunTaskMessage_init_zero                 {TaskInfo_init_zero}
#define KillTaskMessage_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, FrameworkInfo_init_zero}
#define ResourceRequestMessage_init_zero         {{{NULL}, NULL}}
#define ResourceOfferMessage_init_zero           {{{NULL}, NULL}, {{NULL}, NULL}}
#define Offer_init_zero                          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define OfferID_init_zero                        {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ContainerInfo_WASMInfo_wasm_binary_tag   1
#define ContainerInfo_WASMInfo_environment_tag   2
#define FrameworkInfo_name_tag                   2
#define FrameworkInfo_framework_id_tag           3
#define Offer_id_tag                             1
#define Offer_framework_id_tag                   2
#define Offer_agent_id_tag                       3
#define Offer_resources_tag                      5
#define Offer_attributes_tag                     7
#define OfferID_value_tag                        1
#define ResourceOfferMessage_framework_id_tag    1
#define ResourceOfferMessage_offers_tag          2
#define ResourceRequestMessage_framework_id_tag  1
#define Value_Device_device_tag                  1
#define Value_Ranges_range_tag                   1
#define Value_Set_item_tag                       1
#define Value_Text_value_tag                     1
#define AgentInfo_resources_tag                  1
#define AgentInfo_attributes_tag                 2
#define AgentInfo_id_tag                         3
#define AgentInfo_name_tag                       4
#define AgentInfo_ping_rate_tag                  5
#define ContainerInfo_DockerInfo_image_tag       1
#define ContainerInfo_DockerInfo_network_tag     2
#define ContainerInfo_DockerInfo_port_mappings_tag 3
#define ContainerInfo_DockerInfo_force_pull_image_tag 6
#define ContainerInfo_DockerInfo_environment_variables_tag 7
#define ContainerInfo_DockerInfo_PortMapping_host_port_tag 1
#define ContainerInfo_DockerInfo_PortMapping_container_port_tag 2
#define ContainerInfo_DockerInfo_PortMapping_protocol_tag 3
#define ContainerInfo_WASMInfo_EnvironmentVariable_key_tag 1
#define ContainerInfo_WASMInfo_EnvironmentVariable_value_tag 2
#define ContainerInfo_WASMInfo_EnvironmentVariable_str_value_tag 3
#define KillTaskMessage_name_tag                 1
#define KillTaskMessage_task_id_tag              2
#define KillTaskMessage_agent_id_tag             3
#define KillTaskMessage_framework_tag            4
#define Value_Range_begin_tag                    1
#define Value_Range_end_tag                      2
#define Value_Scalar_value_tag                   1
#define Attribute_name_tag                       1
#define Attribute_type_tag                       2
#define Attribute_scalar_tag                     3
#define Attribute_ranges_tag                     4
#define Attribute_text_tag                       5
#define Attribute_set_tag                        6
#define ContainerInfo_type_tag                   1
#define ContainerInfo_docker_tag                 3
#define ContainerInfo_wasm_tag                   5
#define PingAgentMessage_agent_tag               1
#define PingAgentMessage_tasks_tag               2
#define Resource_name_tag                        1
#define Resource_type_tag                        2
#define Resource_scalar_tag                      3
#define Resource_ranges_tag                      4
#define Resource_set_tag                         5
#define Resource_shared_tag                      6
#define Resource_text_tag                        7
#define Resource_device_tag                      8
#define Value_type_tag                           1
#define Value_scalar_tag                         2
#define Value_ranges_tag                         3
#define Value_set_tag                            4
#define Value_text_tag                           5
#define Value_device_tag                         6
#define TaskInfo_name_tag                        1
#define TaskInfo_task_id_tag                     2
#define TaskInfo_agent_id_tag                    3
#define TaskInfo_resources_tag                   4
#define TaskInfo_framework_tag                   5
#define TaskInfo_state_tag                       6
#define TaskInfo_error_message_tag               7
#define TaskInfo_container_tag                   9
#define RunTaskMessage_task_tag                  4
#define PongAgentMessage_agent_id_tag            1
#define PongAgentMessage_run_task_tag            2
#define PongAgentMessage_kill_task_tag           3
#define WrapperMessage_type_tag                  1
#define WrapperMessage_ping_tag                  2
#define WrapperMessage_pong_tag                  3
#define WrapperMessage_run_task_tag              4
#define WrapperMessage_kill_task_tag             5
#define WrapperMessage_offermsg_tag              6
#define WrapperMessage_request_tag               7

/* Struct field encoding specification for nanopb */
#define WrapperMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ping,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pong,              3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  run_task,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  kill_task,         5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  offermsg,          6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  request,           7)
#define WrapperMessage_CALLBACK NULL
#define WrapperMessage_DEFAULT NULL
#define WrapperMessage_ping_MSGTYPE PingAgentMessage
#define WrapperMessage_pong_MSGTYPE PongAgentMessage
#define WrapperMessage_run_task_MSGTYPE RunTaskMessage
#define WrapperMessage_kill_task_MSGTYPE KillTaskMessage
#define WrapperMessage_offermsg_MSGTYPE ResourceOfferMessage
#define WrapperMessage_request_MSGTYPE ResourceRequestMessage

#define PingAgentMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  agent,             1) \
X(a, CALLBACK, REPEATED, MESSAGE,  tasks,             2)
#define PingAgentMessage_CALLBACK pb_default_field_callback
#define PingAgentMessage_DEFAULT NULL
#define PingAgentMessage_agent_MSGTYPE AgentInfo
#define PingAgentMessage_tasks_MSGTYPE TaskInfo

#define PongAgentMessage_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   agent_id,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  run_task,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  kill_task,         3)
#define PongAgentMessage_CALLBACK pb_default_field_callback
#define PongAgentMessage_DEFAULT NULL
#define PongAgentMessage_run_task_MSGTYPE RunTaskMessage
#define PongAgentMessage_kill_task_MSGTYPE KillTaskMessage

#define AgentInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  resources,         1) \
X(a, CALLBACK, REPEATED, MESSAGE,  attributes,        2) \
X(a, CALLBACK, OPTIONAL, STRING,   id,                3) \
X(a, CALLBACK, OPTIONAL, STRING,   name,              4) \
X(a, STATIC,   OPTIONAL, INT32,    ping_rate,         5)
#define AgentInfo_CALLBACK pb_default_field_callback
#define AgentInfo_DEFAULT NULL
#define AgentInfo_resources_MSGTYPE Resource
#define AgentInfo_attributes_MSGTYPE Attribute

#define Resource_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, UENUM,    type,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scalar,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ranges,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  set,               5) \
X(a, STATIC,   OPTIONAL, BOOL,     shared,            6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  text,              7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,            8)
#define Resource_CALLBACK pb_default_field_callback
#define Resource_DEFAULT NULL
#define Resource_scalar_MSGTYPE Value_Scalar
#define Resource_ranges_MSGTYPE Value_Ranges
#define Resource_set_MSGTYPE Value_Set
#define Resource_text_MSGTYPE Value_Text
#define Resource_device_MSGTYPE Value_Device

#define Attribute_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, STATIC,   REQUIRED, UENUM,    type,              2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scalar,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ranges,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  text,              5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  set,               6)
#define Attribute_CALLBACK pb_default_field_callback
#define Attribute_DEFAULT NULL
#define Attribute_scalar_MSGTYPE Value_Scalar
#define Attribute_ranges_MSGTYPE Value_Ranges
#define Attribute_text_MSGTYPE Value_Text
#define Attribute_set_MSGTYPE Value_Set

#define Value_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scalar,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  ranges,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  set,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  text,              5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,            6)
#define Value_CALLBACK NULL
#define Value_DEFAULT NULL
#define Value_scalar_MSGTYPE Value_Scalar
#define Value_ranges_MSGTYPE Value_Ranges
#define Value_set_MSGTYPE Value_Set
#define Value_text_MSGTYPE Value_Text
#define Value_device_MSGTYPE Value_Device

#define Value_Scalar_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, DOUBLE,   value,             1)
#define Value_Scalar_CALLBACK NULL
#define Value_Scalar_DEFAULT NULL

#define Value_Range_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   begin,             1) \
X(a, STATIC,   REQUIRED, UINT64,   end,               2)
#define Value_Range_CALLBACK NULL
#define Value_Range_DEFAULT NULL

#define Value_Ranges_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  range,             1)
#define Value_Ranges_CALLBACK pb_default_field_callback
#define Value_Ranges_DEFAULT NULL
#define Value_Ranges_range_MSGTYPE Value_Range

#define Value_Set_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, STRING,   item,              1)
#define Value_Set_CALLBACK pb_default_field_callback
#define Value_Set_DEFAULT NULL

#define Value_Text_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   value,             1)
#define Value_Text_CALLBACK pb_default_field_callback
#define Value_Text_DEFAULT NULL

#define Value_Device_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   device,            1)
#define Value_Device_CALLBACK pb_default_field_callback
#define Value_Device_DEFAULT NULL

#define ContainerInfo_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  docker,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  wasm,              5)
#define ContainerInfo_CALLBACK NULL
#define ContainerInfo_DEFAULT (const pb_byte_t*)"\x08\x01\x00"
#define ContainerInfo_docker_MSGTYPE ContainerInfo_DockerInfo
#define ContainerInfo_wasm_MSGTYPE ContainerInfo_WASMInfo

#define ContainerInfo_DockerInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   image,             1) \
X(a, STATIC,   OPTIONAL, UENUM,    network,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  port_mappings,     3) \
X(a, STATIC,   OPTIONAL, BOOL,     force_pull_image,   6) \
X(a, CALLBACK, REPEATED, STRING,   environment_variables,   7)
#define ContainerInfo_DockerInfo_CALLBACK pb_default_field_callback
#define ContainerInfo_DockerInfo_DEFAULT (const pb_byte_t*)"\x10\x01\x00"
#define ContainerInfo_DockerInfo_port_mappings_MSGTYPE ContainerInfo_DockerInfo_PortMapping

#define ContainerInfo_DockerInfo_PortMapping_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   host_port,         1) \
X(a, STATIC,   REQUIRED, UINT32,   container_port,    2) \
X(a, CALLBACK, OPTIONAL, STRING,   protocol,          3)
#define ContainerInfo_DockerInfo_PortMapping_CALLBACK pb_default_field_callback
#define ContainerInfo_DockerInfo_PortMapping_DEFAULT NULL

#define ContainerInfo_WASMInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    wasm_binary,       1) \
X(a, CALLBACK, REPEATED, MESSAGE,  environment,       2)
#define ContainerInfo_WASMInfo_CALLBACK pb_default_field_callback
#define ContainerInfo_WASMInfo_DEFAULT NULL
#define ContainerInfo_WASMInfo_environment_MSGTYPE ContainerInfo_WASMInfo_EnvironmentVariable

#define ContainerInfo_WASMInfo_EnvironmentVariable_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   key,               1) \
X(a, STATIC,   OPTIONAL, INT32,    value,             2) \
X(a, CALLBACK, OPTIONAL, STRING,   str_value,         3)
#define ContainerInfo_WASMInfo_EnvironmentVariable_CALLBACK pb_default_field_callback
#define ContainerInfo_WASMInfo_EnvironmentVariable_DEFAULT NULL

#define FrameworkInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              2) \
X(a, CALLBACK, OPTIONAL, STRING,   framework_id,      3)
#define FrameworkInfo_CALLBACK pb_default_field_callback
#define FrameworkInfo_DEFAULT NULL

#define TaskInfo_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, CALLBACK, REQUIRED, STRING,   task_id,           2) \
X(a, CALLBACK, REQUIRED, STRING,   agent_id,          3) \
X(a, CALLBACK, REPEATED, MESSAGE,  resources,         4) \
X(a, STATIC,   REQUIRED, MESSAGE,  framework,         5) \
X(a, STATIC,   OPTIONAL, UENUM,    state,             6) \
X(a, CALLBACK, OPTIONAL, STRING,   error_message,     7) \
X(a, STATIC,   REQUIRED, MESSAGE,  container,         9)
#define TaskInfo_CALLBACK pb_default_field_callback
#define TaskInfo_DEFAULT NULL
#define TaskInfo_resources_MSGTYPE Resource
#define TaskInfo_framework_MSGTYPE FrameworkInfo
#define TaskInfo_container_MSGTYPE ContainerInfo

#define RunTaskMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  task,              4)
#define RunTaskMessage_CALLBACK NULL
#define RunTaskMessage_DEFAULT NULL
#define RunTaskMessage_task_MSGTYPE TaskInfo

#define KillTaskMessage_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, CALLBACK, REQUIRED, STRING,   task_id,           2) \
X(a, CALLBACK, REQUIRED, STRING,   agent_id,          3) \
X(a, STATIC,   REQUIRED, MESSAGE,  framework,         4)
#define KillTaskMessage_CALLBACK pb_default_field_callback
#define KillTaskMessage_DEFAULT NULL
#define KillTaskMessage_framework_MSGTYPE FrameworkInfo

#define ResourceRequestMessage_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   framework_id,      1)
#define ResourceRequestMessage_CALLBACK pb_default_field_callback
#define ResourceRequestMessage_DEFAULT NULL

#define ResourceOfferMessage_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   framework_id,      1) \
X(a, CALLBACK, REPEATED, MESSAGE,  offers,            2)
#define ResourceOfferMessage_CALLBACK pb_default_field_callback
#define ResourceOfferMessage_DEFAULT NULL
#define ResourceOfferMessage_offers_MSGTYPE Offer

#define Offer_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   id,                1) \
X(a, CALLBACK, REQUIRED, STRING,   framework_id,      2) \
X(a, CALLBACK, REQUIRED, STRING,   agent_id,          3) \
X(a, CALLBACK, REPEATED, MESSAGE,  resources,         5) \
X(a, CALLBACK, REPEATED, MESSAGE,  attributes,        7)
#define Offer_CALLBACK pb_default_field_callback
#define Offer_DEFAULT NULL
#define Offer_resources_MSGTYPE Resource
#define Offer_attributes_MSGTYPE Attribute

#define OfferID_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   value,             1)
#define OfferID_CALLBACK pb_default_field_callback
#define OfferID_DEFAULT NULL

extern const pb_msgdesc_t WrapperMessage_msg;
extern const pb_msgdesc_t PingAgentMessage_msg;
extern const pb_msgdesc_t PongAgentMessage_msg;
extern const pb_msgdesc_t AgentInfo_msg;
extern const pb_msgdesc_t Resource_msg;
extern const pb_msgdesc_t Attribute_msg;
extern const pb_msgdesc_t Value_msg;
extern const pb_msgdesc_t Value_Scalar_msg;
extern const pb_msgdesc_t Value_Range_msg;
extern const pb_msgdesc_t Value_Ranges_msg;
extern const pb_msgdesc_t Value_Set_msg;
extern const pb_msgdesc_t Value_Text_msg;
extern const pb_msgdesc_t Value_Device_msg;
extern const pb_msgdesc_t ContainerInfo_msg;
extern const pb_msgdesc_t ContainerInfo_DockerInfo_msg;
extern const pb_msgdesc_t ContainerInfo_DockerInfo_PortMapping_msg;
extern const pb_msgdesc_t ContainerInfo_WASMInfo_msg;
extern const pb_msgdesc_t ContainerInfo_WASMInfo_EnvironmentVariable_msg;
extern const pb_msgdesc_t FrameworkInfo_msg;
extern const pb_msgdesc_t TaskInfo_msg;
extern const pb_msgdesc_t RunTaskMessage_msg;
extern const pb_msgdesc_t KillTaskMessage_msg;
extern const pb_msgdesc_t ResourceRequestMessage_msg;
extern const pb_msgdesc_t ResourceOfferMessage_msg;
extern const pb_msgdesc_t Offer_msg;
extern const pb_msgdesc_t OfferID_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WrapperMessage_fields &WrapperMessage_msg
#define PingAgentMessage_fields &PingAgentMessage_msg
#define PongAgentMessage_fields &PongAgentMessage_msg
#define AgentInfo_fields &AgentInfo_msg
#define Resource_fields &Resource_msg
#define Attribute_fields &Attribute_msg
#define Value_fields &Value_msg
#define Value_Scalar_fields &Value_Scalar_msg
#define Value_Range_fields &Value_Range_msg
#define Value_Ranges_fields &Value_Ranges_msg
#define Value_Set_fields &Value_Set_msg
#define Value_Text_fields &Value_Text_msg
#define Value_Device_fields &Value_Device_msg
#define ContainerInfo_fields &ContainerInfo_msg
#define ContainerInfo_DockerInfo_fields &ContainerInfo_DockerInfo_msg
#define ContainerInfo_DockerInfo_PortMapping_fields &ContainerInfo_DockerInfo_PortMapping_msg
#define ContainerInfo_WASMInfo_fields &ContainerInfo_WASMInfo_msg
#define ContainerInfo_WASMInfo_EnvironmentVariable_fields &ContainerInfo_WASMInfo_EnvironmentVariable_msg
#define FrameworkInfo_fields &FrameworkInfo_msg
#define TaskInfo_fields &TaskInfo_msg
#define RunTaskMessage_fields &RunTaskMessage_msg
#define KillTaskMessage_fields &KillTaskMessage_msg
#define ResourceRequestMessage_fields &ResourceRequestMessage_msg
#define ResourceOfferMessage_fields &ResourceOfferMessage_msg
#define Offer_fields &Offer_msg
#define OfferID_fields &OfferID_msg

/* Maximum encoded size of messages (where known) */
/* WrapperMessage_size depends on runtime parameters */
/* PingAgentMessage_size depends on runtime parameters */
/* PongAgentMessage_size depends on runtime parameters */
/* AgentInfo_size depends on runtime parameters */
/* Resource_size depends on runtime parameters */
/* Attribute_size depends on runtime parameters */
/* Value_size depends on runtime parameters */
#define Value_Scalar_size                        9
#define Value_Range_size                         22
/* Value_Ranges_size depends on runtime parameters */
/* Value_Set_size depends on runtime parameters */
/* Value_Text_size depends on runtime parameters */
/* Value_Device_size depends on runtime parameters */
/* ContainerInfo_size depends on runtime parameters */
/* ContainerInfo_DockerInfo_size depends on runtime parameters */
/* ContainerInfo_DockerInfo_PortMapping_size depends on runtime parameters */
/* ContainerInfo_WASMInfo_size depends on runtime parameters */
/* ContainerInfo_WASMInfo_EnvironmentVariable_size depends on runtime parameters */
/* FrameworkInfo_size depends on runtime parameters */
/* TaskInfo_size depends on runtime parameters */
/* RunTaskMessage_size depends on runtime parameters */
/* KillTaskMessage_size depends on runtime parameters */
/* ResourceRequestMessage_size depends on runtime parameters */
/* ResourceOfferMessage_size depends on runtime parameters */
/* Offer_size depends on runtime parameters */
/* OfferID_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
