---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: edge-rm-ns
  name: edge-rm-agent
  labels:
    app: edge-rm
    component: agent
spec:
  selector:
    matchLabels:
      run: edge-rm-agent
  replicas: 1
  template:
    metadata:
      namespace: edge-rm-ns
      labels:
        run: edge-rm-agent
    spec:
      containers:
      - name: edge-rm-agent
        image: lab11/edge-rm-agent:latest
        imagePullPolicy: Always
        env:
        # the magic to make give access to the docker-in-docker container:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: CENTRAL_HOST
          value: edge-rm-central-svc
        # do we need the edge-rm-central SERVICE_PORT? 
        - name: CENTRAL_PORT
          value: "80"
        # attempt to get rid of delay before agent output shows up in kubectl logs
        # (probably won't help as supposedly this is default behavior as of python 3.7)
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONIOENCODING
          value: UTF-8
      - name: dind
        # note: newer versions of dind do not listen on 2375, only TLS on 2376
        image: docker:18.09-dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
      volumes:
        - name: dind-storage
          emptyDir: {}
