#max memory to allow the agent to use
maxMem: 128MB

#max CPU to allow the agent to use. Currently unitless
maxCPUs: 1

#max Disk to allow the agent to use
maxDisk: 1GB

pingRate: 3000

## If domain is set this is a global accessible domain or IP
#domain: test.com
#
## A list of devices for the docker container
devices: 
 - name: picam
   #the device ID should be something unique about it - it's unique name in the system
   id: /dev/vchiq
   shared: True
   dockerDevices:
    - hostPath: /dev/vchiq
      containerPath: /dev/vchiq
      permission: rwm
#   dockerVolumes:
#    - hostPath: /opt/vc
#      containerPath: /opt/vc
#      permission: ro
#   environmentVariables: 
#    - "LD_LIBRARY_PATH=/opt/vc/lib"